#the way this works is if your ping is below 50 ms, then it is considered excellent.
#if it is between 50 ms and 100 ms, then it is good, and subsequently works the same way
#for the other values.
ping-thresholds:
  excellent: 50
  good: 100
  medium: 200
  bad: 300

