name: PingPlayer
version: '1.0.0'
main: me.honeyberries.pingPlayer.PingPlayer
api-version: '1.13'
authors: [ HoneyBerries ]
commands:
  ping:
    description: "Lets you ping a player to get their latency! If no argument given, then gets your ping!"
    usage: "/ping <playername>"
    aliases: []
    permission: pingPlayer.ping
    permission-message: "You don't have the permission to ping a player!"
permissions:
  pingPlayer.ping:
    description: "This permission allows players to ping another player for latency!"
    default: true
  pingPlayer.reload:
    description: "This permission allows players to reload the config"
    default: op
