name: PingPlayer
version: '1.1.0'
main: me.honeyberries.pingPlayer.PingPlayer
api-version: '1.21'
authors: [ HoneyBerries ]
folia-supported: true
commands:
  pingplayer:
    description: "Admin commands for the Ping Player plugin"
    usage: "/pingplayer <action>"
    aliases: [ ]
  ping:
    description: "Lets you ping a player to get their latency! If no argument given, then gets your ping!"
    usage: "/ping <playername>"
    aliases: [ ]
  ip:
    description: Retrieves the IP address of a specified player.
    aliases: [getip, ipaddress]
    usage: /ip <player>
permissions:
  pingplayer.ping:
    description: "This permission allows players to ping another player for latency!"
    default: true
  pingplayer.ip:
    description: "Allows you to get the IP address of a player"
    default: op
  pingplayer.settings:
    description: "Allows you to edit the settings of this plugin"
    default: op
  pingplayer.viewping:
    description: "Allows you to view the ping of another player on the tab list"
    default: true

